name: test

on: 
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        tox_env:
          - py27
          - py36
          - py37
          - py38
          - py39
          - pypy3
    steps:
      - uses: actions/checkout@v2
      - name: Fedora Tox with ${{ matrix.tox_env }}
        uses: fedora-python/tox-github-action@v0.4
        with:
          tox_env: ${{ matrix.tox_env }}
      - uses: actions/setup-python@v2
      - uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip
  
  deploy:
    name: Build deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: casperdcl/deploy-pypi@v1
        if: github.event_name == 'push' && startsWith(github.event.ref, 'refs/tags')
        with:
          password: ${{ secrets.PYPI_TOKEN }}
          build: true
      